# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Speedy/epitech/network/strat

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Speedy/epitech/network/strat

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Speedy/epitech/network/strat/CMakeFiles /home/Speedy/epitech/network/strat/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Speedy/epitech/network/strat/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named strat

# Build rule for target.
strat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 strat
.PHONY : strat

# fast build rule for target.
strat/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/build
.PHONY : strat/fast

example/Game/Game.o: example/Game/Game.cpp.o

.PHONY : example/Game/Game.o

# target to build an object file
example/Game/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/example/Game/Game.cpp.o
.PHONY : example/Game/Game.cpp.o

example/Game/Game.i: example/Game/Game.cpp.i

.PHONY : example/Game/Game.i

# target to preprocess a source file
example/Game/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/example/Game/Game.cpp.i
.PHONY : example/Game/Game.cpp.i

example/Game/Game.s: example/Game/Game.cpp.s

.PHONY : example/Game/Game.s

# target to generate assembly for a file
example/Game/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/example/Game/Game.cpp.s
.PHONY : example/Game/Game.cpp.s

example/Game/event.o: example/Game/event.cpp.o

.PHONY : example/Game/event.o

# target to build an object file
example/Game/event.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/example/Game/event.cpp.o
.PHONY : example/Game/event.cpp.o

example/Game/event.i: example/Game/event.cpp.i

.PHONY : example/Game/event.i

# target to preprocess a source file
example/Game/event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/example/Game/event.cpp.i
.PHONY : example/Game/event.cpp.i

example/Game/event.s: example/Game/event.cpp.s

.PHONY : example/Game/event.s

# target to generate assembly for a file
example/Game/event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/example/Game/event.cpp.s
.PHONY : example/Game/event.cpp.s

example/main.o: example/main.cpp.o

.PHONY : example/main.o

# target to build an object file
example/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/example/main.cpp.o
.PHONY : example/main.cpp.o

example/main.i: example/main.cpp.i

.PHONY : example/main.i

# target to preprocess a source file
example/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/example/main.cpp.i
.PHONY : example/main.cpp.i

example/main.s: example/main.cpp.s

.PHONY : example/main.s

# target to generate assembly for a file
example/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/example/main.cpp.s
.PHONY : example/main.cpp.s

src/Core/Core.o: src/Core/Core.cpp.o

.PHONY : src/Core/Core.o

# target to build an object file
src/Core/Core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/src/Core/Core.cpp.o
.PHONY : src/Core/Core.cpp.o

src/Core/Core.i: src/Core/Core.cpp.i

.PHONY : src/Core/Core.i

# target to preprocess a source file
src/Core/Core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/src/Core/Core.cpp.i
.PHONY : src/Core/Core.cpp.i

src/Core/Core.s: src/Core/Core.cpp.s

.PHONY : src/Core/Core.s

# target to generate assembly for a file
src/Core/Core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/src/Core/Core.cpp.s
.PHONY : src/Core/Core.cpp.s

src/Core/change_scene.o: src/Core/change_scene.cpp.o

.PHONY : src/Core/change_scene.o

# target to build an object file
src/Core/change_scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/src/Core/change_scene.cpp.o
.PHONY : src/Core/change_scene.cpp.o

src/Core/change_scene.i: src/Core/change_scene.cpp.i

.PHONY : src/Core/change_scene.i

# target to preprocess a source file
src/Core/change_scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/src/Core/change_scene.cpp.i
.PHONY : src/Core/change_scene.cpp.i

src/Core/change_scene.s: src/Core/change_scene.cpp.s

.PHONY : src/Core/change_scene.s

# target to generate assembly for a file
src/Core/change_scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/src/Core/change_scene.cpp.s
.PHONY : src/Core/change_scene.cpp.s

src/Object/AObject.o: src/Object/AObject.cpp.o

.PHONY : src/Object/AObject.o

# target to build an object file
src/Object/AObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/src/Object/AObject.cpp.o
.PHONY : src/Object/AObject.cpp.o

src/Object/AObject.i: src/Object/AObject.cpp.i

.PHONY : src/Object/AObject.i

# target to preprocess a source file
src/Object/AObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/src/Object/AObject.cpp.i
.PHONY : src/Object/AObject.cpp.i

src/Object/AObject.s: src/Object/AObject.cpp.s

.PHONY : src/Object/AObject.s

# target to generate assembly for a file
src/Object/AObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/src/Object/AObject.cpp.s
.PHONY : src/Object/AObject.cpp.s

src/Scene/AScene.o: src/Scene/AScene.cpp.o

.PHONY : src/Scene/AScene.o

# target to build an object file
src/Scene/AScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/src/Scene/AScene.cpp.o
.PHONY : src/Scene/AScene.cpp.o

src/Scene/AScene.i: src/Scene/AScene.cpp.i

.PHONY : src/Scene/AScene.i

# target to preprocess a source file
src/Scene/AScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/src/Scene/AScene.cpp.i
.PHONY : src/Scene/AScene.cpp.i

src/Scene/AScene.s: src/Scene/AScene.cpp.s

.PHONY : src/Scene/AScene.s

# target to generate assembly for a file
src/Scene/AScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strat.dir/build.make CMakeFiles/strat.dir/src/Scene/AScene.cpp.s
.PHONY : src/Scene/AScene.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... strat"
	@echo "... example/Game/Game.o"
	@echo "... example/Game/Game.i"
	@echo "... example/Game/Game.s"
	@echo "... example/Game/event.o"
	@echo "... example/Game/event.i"
	@echo "... example/Game/event.s"
	@echo "... example/main.o"
	@echo "... example/main.i"
	@echo "... example/main.s"
	@echo "... src/Core/Core.o"
	@echo "... src/Core/Core.i"
	@echo "... src/Core/Core.s"
	@echo "... src/Core/change_scene.o"
	@echo "... src/Core/change_scene.i"
	@echo "... src/Core/change_scene.s"
	@echo "... src/Object/AObject.o"
	@echo "... src/Object/AObject.i"
	@echo "... src/Object/AObject.s"
	@echo "... src/Scene/AScene.o"
	@echo "... src/Scene/AScene.i"
	@echo "... src/Scene/AScene.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

